name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this to the appropriate branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20 # Use the appropriate Vercel action version
        with:
          vercel-token:  ${{ secrets.VERCEL_TOKEN }} # Add your Vercel token as a GitHub secret
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
